services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "1024G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    networks:
      vdsm:
        ipv4_address: 192.168.1.101

    volumes:
      - /mnt/data/VDSM:/storage
    restart: unless-stopped
    stop_grace_period: 2m
networks:
  vdsm:
    external: true